<?php $this->headTitle()->append("Tutorials"); ?>
<h2 id="contentTitle">Formatting text content</h2>
<p>Most input where you enter a block of text, such as set description or user profile page content can be formatted using an extended Markdown syntax. This tutorial will introduce you to Markdown and descibe of all the extensions provided by WebDrafter.</p>
<h3>Introduction to Markdown</h3>
https://guides.github.com/features/mastering-markdown/
<h3>Magic symbols</h3>
These are all the Magic: the Gathering symbols that you can use in text. The symbols will correspond in size to currrent font size (for example, if you include a symbol in a heading, it will be enlarged appropriately).
<table>
  <tr>
    <th>Syntax</th>
    <th>Result</th>
    <th>Name</th>
    <th>Note</th>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[W]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg white"></i></span></td>
    <td>Colored mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[bW]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg plains"></i></span></td>
    <td>Monochrome mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[1]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg mana-1"></i></span></td>
    <td>Generic mana</td>
    <td>Available for numbers 0-20, X, Y and Z.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[T]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg tap"></i></span></td>
    <td>Tap</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[UT]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg untap"></i></span></td>
    <td>Untap</td>
    <td>Also available under <pre class="code-sample-inline">[Q]</pre>.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[WU]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg hybrid-wu"></i></span></td>
    <td>Hybrid mana</td>
    <td>Available for all 10 color pairs, in either order.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[2W]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg hybrid-2w"></i></span></td>
    <td>Twobrid mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[PW]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg phyrexian-w"></i></span></td>
    <td>Phyrexian mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[P]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg phyrexian"></i></span></td>
    <td>Phyrexian mana (colorless)</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[S]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg snow"></i></span></td>
    <td>Snow mana</td>
    <td>&nbsp;</td>
  </tr>
</table>
<h3>Referencing cards</h3>
<p>Unlike on traditional Magic: the Gathering message boards, many sets can contain different cards with the same name. Additionally, each set can exist in multiple versions. Bcause of this, the syntax used to reference cards on WebDrafter is slightly more complicated. Card refernce will be transformed into a hyperlink leading to that card's page, and will also display image of that card when the user hover with his mouse cursor over the link.</p>
<p>The most basic syntax is this:</p>
<pre class="code-sample">[[Lightning Bolt]]</pre>
<p>This only works when used in a context where it is completely obvious, which set the piece of text content relates to - on set page (the lastest version of the card will be referenced) or on set version (the card fom that version will be referenced).</p>
<p>You can also specify to which set the card belongs to using that set's URL name (applies for set with URL <span class="explicit-url"><?php echo $this->url('browse-set', array('url_name' => 'modern-masters-2015'), array('force_canonical' => true))?></span>):
<pre class="code-sample">[[modern-masters-2015:Lightning Bolt]]</pre>
<p>This will always reference the newest version of the card.</p>
<p>Next step is to specify which version of the card is referenced, by adding that version's URL name (considering version with URL <span class="explicit-url"><?php echo $this->url('browse-version', array('url_name' => 'modern-masters-2015', 'version_url_name' => 'version-3'), array('force_canonical' => true))?></span>):</p>
<pre class="code-sample">[[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<p>You can also specify text of the link, without affecting which card that link points to using the pipe symbol (works in combination with any of the above):</p>
<pre class="code-sample">I love [[modern-masters-2015:version-3:Lightning Bolt|bolting]] my opponents!</pre>
<p>If you want to include an image of the card, instead of a link, you can add an exclamation mark symbol before the initial [[ (also works with any of the above notations):</p>
<pre class="code-sample">![[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<p>Additionally, you can set the image to align left or right:</p>
<pre class="code-sample">!l[[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<pre class="code-sample">!r[[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<p>Either of these will also make text flow nicely around the card image (if you don't specify alignment, the image will be placed inline into the text). </p>

<h3>Font Awesome</h3>
<p>Font Awesome is publically available library of <a href="https://fortawesome.github.io/Font-Awesome/icons/" title="Font Awesome" target="_blank">hundreds of symbolic icons</a> for web applications. You can use any of these icons using following syntax, where <span class="explicit-url">fa-thumbs-up</span> is name of the icon:</p>
<pre class="code-sample">[fa-thumbs-up]</pre> 
Which will result in this: <i class="fa fa-thumbs-up"></i>. All icons from all FA versions up to 4.4.0 are supported. As with the Magic symbols, all of these will scale with current size of the text. :) and :( will be transformed into appropriate Font Awesome emotes even without the explicit syntax.

<h2 id="contentTitle">How to import sets into WebDrafter</h2>
<div class="tutorial">
This tutorial assumes you created your custom set using <a href="http://magicseteditor.sourceforge.net/">Magic Set Editor 2</a>.

<ol>
	<li><strong>Export card data file for WebDrafter</strong>
		<ol>
			<li>Download <a href="http://puu.sh/i8GMt/28e82db942.zip">WebDrafter export template</a> for MSE.</li>
			<li>Extract the archive into the "data" directory in the location where MSE2 is installed. Restart MSE, if it was running.</li>
			<li>In MSE, go to "File"->"Export"->"HTML". Click OK and choose an export location. <br /><img src="http://puu.sh/j3Swk/329dda2e6c.png" />
	
		</ol>
	</li>
	<li><strong>Export card images</strong>
		<ol>
			<li>In MSE, go to "File"->"Export"->"All card images".</li>
			<li>If you want, you can change the file extension to .png for improved image quality (but bigger image files). <br /><img src="http://puu.sh/j3SOd/d5afb1ec01.png">
			<li>Click OK and choose a directory where the files will be exported.
		</ol>
	</li>
	<li><strong>Publish card images on Google Drive</strong>
		<ol>
			<li>If you don't have Google account, <a href="https://accounts.google.com/signup?hl=cs">create one</a>. It is completely free.</li>
			<li>Download and install <a href="https://www.google.com/intl/cs_cz/drive/download/">Google Drive</a> application on your computer.</li>
			<li>Open File Explorer and go to Google Drive (it should be in the Favorites section in the left panel, if you have recent version of Windows). If you can't find it, go to tray bar (on bottom left of the screen, just next of the clock) and look for a Google Drive icon (a green-yellow-blue triangle), click it and click "Open Google Drive folder".
			<li>Create a folder where you will put the card images. I recommend to have a nice folder structure, something like "Custom Sets/Khans of Tarkir/Khans of Tarkir 1.0". It is a very good idea to keep older versions of the set intact, so that WebDrafter can keep older drafts in its archive.
			<li>Copy the card images into the prepared folder. Next time, you can have MSE generate the card images straight onto the Google Drive.
			<li>Wait until Google Drive uploads the images into the cloud. You can see the synchronization status when you click on the Google Drive icon in the tray bar. <br /><img src="http://puu.sh/j3TU7/47cd2a5137.png" />
		</ol>
	</li>
	<li><strong>Import the set into WebDrafter</strong>
		<ol>
			<li>Go the the <a href="http://webdrafter.geogen.cz">main page of WebDrafter</a>.
			<li>Click "login". You will be redirected to a Google page. If you are not yet logged into Google, log in. Then authorize WebDrafter. You will be redirected back to the application, the the main page of the member area.
			<li>Click create set.
			<li>Fill in set name (the name must be unique across all registered sets, this includes retired sets. I recomment to include version number or date) and set code (that doesn't have to be unique). 
			<li>Optionally, you can fill in "Information URL". This should contain a link to the set's web page (if it has any) or related discussion thread - simply a location where curious players can find additional information about the set.
			<li>Click the "Pick from Google Drive" button. A window opens with the contents of your Google Drive. Choose the folder where your card images are located and click "Select". <br /><img src="http://puu.sh/j3UsN/b520be0d4f.png">.
			<li>Depending on your card image format, choose appropriate option in "Art file name format".
			<li>If you have create a Cockatrice package, upload it to some place on the internet and put the link into "Download URL".
			<li>Click "Choose file", find your set export file, and click OK. 
			<li>Click "Create".
			<li>You should now be back on the main page of the member area and the application should be informing you "Set create". You should be able to see the set in the list of "Sets you created". You can click the set name to inspect it or go straight to hosting an event with it!
			<li>If you created the set, but something is wrong, go the member area, and click "Retire" next to the set name. This will remove the set from all listings, but will keep any events that used it intact.
		</ol>
	</li>
</ol>
