<?php $this->headTitle()->append("Tutorials"); ?>
<h2 id="contentTitle">Tutorials</h2>
<ol>
	<li><a href="#formatting">Formatting text content</a></li>
	<li><a href="#querying">Search reference</a></li>
	<li><a href="#set-import">How to import sets into PlaneSculptors</a></li>
</ol>
<a name="formatting"></a>
<h3>Formatting text content</h3>
<p>Most input where you enter a block of text, such as set description or user profile page content can be formatted using an extended Markdown syntax. This tutorial will introduce you to Markdown and descibe of all the extensions provided by WebDrafter.</p>
<h4>Introduction to Markdown</h4>
<p>Markdown is a markup language used to format text on websites like Reddit and GitHub. You can see a quick "cheat sheet" below. For more advanced guide see <a hred="https://guides.github.com/features/mastering-markdown/" title="Mastering Markdown">Mastering Markdown</a>. In addition to standard Markdown, WebDrafter also supports GitHub-style tables (see example below).</p> 
<pre class="code-sample"># Heading level 1
## Heading level 2
### Heading level 3

*Italic text*
**Bold text**
~~Strikethrough~~

* Unordered list item
* Unordered list item
* Unordered list item

1. Ordered list item
2. Ordered list item
3. Ordered list item

[Link title](http://www.google.com)
![Image title](http://www.github.com/images/logo.png)

First Header | Second Header | Third header
------------ | ------------- | ------------
Content from cell 1 | Content from cell 2 | Content from cell 3
Content from cell 4 | Content from cell 5 | Content from cell 6</pre>
<a name="symbols"></a>
<h4>Magic symbols</h4>
<p>These are all the Magic: the Gathering symbols that you can use in text. The symbols will correspond in size to currrent font size (for example, if you include a symbol in a heading, it will be enlarged appropriately).</p>
<table>
  <tr>
    <th>Syntax</th>
    <th>Result</th>
    <th>Name</th>
    <th>Note</th>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[C]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg colorless"></i></span></td>
    <td>Colorless mana</td>
    <td>&nbsp;</td>
  </tr>  
  <tr>
    <td><pre class="code-sample-inline">[W]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg white"></i></span></td>
    <td>Colored mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[bW]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg plains"></i></span></td>
    <td>Monochrome mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[1]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg mana-1"></i></span></td>
    <td>Generic mana</td>
    <td>Available for numbers 0-20, X, Y and Z.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[T]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg tap"></i></span></td>
    <td>Tap</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[UT]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg untap"></i></span></td>
    <td>Untap</td>
    <td>Also available under <pre class="code-sample-inline">[Q]</pre>.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[WU]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg hybrid-wu"></i></span></td>
    <td>Hybrid mana</td>
    <td>Available for all 10 color pairs, in either order.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[2W]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg hybrid-2w"></i></span></td>
    <td>Twobrid mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[PW]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg phyrexian-w"></i></span></td>
    <td>Phyrexian mana</td>
    <td>Available for all 5 colors.</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[P]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg phyrexian"></i></span></td>
    <td>Phyrexian mana (colorless)</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td><pre class="code-sample-inline">[S]</pre></td>
    <td><span class="icon-wrapper"><i class="mtg snow"></i></span></td>
    <td>Snow mana</td>
    <td>&nbsp;</td>
  </tr>
</table>
<p>Most input where you enter a block of text, such as set description or user profile page content can be formatted using an extended Markdown syntax. This tutorial will introduce you to Markdown and descibe of all the extensions provided by WebDrafter.</p>
<h4>Introduction to Markdown</h4>
<h4>Referencing cards</h4>
<p>Unlike on traditional Magic: the Gathering message boards, many sets can contain different cards with the same name. Additionally, each set can exist in multiple versions. Because of this, the syntax used to reference cards on WebDrafter is slightly more complicated. Card refernce will be transformed into a hyperlink leading to that card's page, and will also display image of that card when the user hover with his mouse cursor over the link.</p>
<p>The most basic syntax is this:</p>
<pre class="code-sample">[[Lightning Bolt]]</pre>
<p>This only works when used in a context where it is completely obvious, which set the piece of text content relates to - on set page (the lastest version of the card will be referenced) or on set version (the card fom that version will be referenced).</p>
<p>You can also specify to which set the card belongs to using that set's URL name (applies for set with URL <span class="explicit-url"><?php echo $this->url('browse-set', array('url_name' => 'modern-masters-2015'), array('force_canonical' => true))?></span>):
<pre class="code-sample">[[modern-masters-2015:Lightning Bolt]]</pre>
<p>This will always reference the newest version of the card.</p>
<p>Next step is to specify which version of the card is referenced, by adding that version's URL name (considering version with URL <span class="explicit-url"><?php echo $this->url('browse-version', array('url_name' => 'modern-masters-2015', 'version_url_name' => 'version-3'), array('force_canonical' => true))?></span>):</p>
<pre class="code-sample">[[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<p>You can also specify text of the link, without affecting which card that link points to using the pipe symbol (works in combination with any of the above):</p>
<pre class="code-sample">I love [[modern-masters-2015:version-3:Lightning Bolt|bolting]] my opponents!</pre>
<p>If you want to include an image of the card, instead of a link, you can add an exclamation mark symbol before the initial [[ (also works with any of the above notations):</p>
<pre class="code-sample">![[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<p>Additionally, you can set the image to align left or right:</p>
<pre class="code-sample">!l[[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<pre class="code-sample">!r[[modern-masters-2015:version-3:Lightning Bolt]]</pre>
<p>Either of these will also make text flow nicely around the card image (if you don't specify alignment, the image will be placed inline into the text). </p>

<h4>Font Awesome</h4>
<p>Font Awesome is publically available library of <a href="https://fortawesome.github.io/Font-Awesome/icons/" title="Font Awesome" target="_blank">hundreds of symbolic icons</a> for web applications. You can use any of these icons using following syntax, where <span class="explicit-url">fa-thumbs-up</span> is name of the icon:</p>
<pre class="code-sample">[fa-thumbs-up]</pre> 
<p>Which will result in this: <i class="fa fa-thumbs-up"></i>. All icons from all FA versions up to 4.4.0 are supported. As with the Magic symbols, all of these will scale with current size of the text. :) and :( will be transformed into appropriate Font Awesome emotes even without the explicit syntax.</p>
<h4>Inline HTML</h4>
<p>You can use HTML arbitrarily in combination with any other syntax offered by WebDrafter, with inline CSS being allowed as well. With HTML, you can achieve many things that the simple markup syntax wouldn't allow you to. Please take care not to interfere with layout of the website, otherwise yoru content will be taken down.<p>
<h4>Page source code</h4>
<p>You can view the source code of any user-submitted formatted text on any page (user profile, set page etc.) by adding "?source" to the URL of that page, for example <span class="explicit-url"><?php echo $this->url('browse-version', array('url_name' => 'modern-masters-2015', 'version_url_name' => 'version-3'), array('force_canonical' => true))?></span>. If that page specifies a hash fagment (<span class="explicit-url">#detail</span>), always add the source parameter before it.</p>
<a name="querying"></a>
<h3 id="contentTitle">Search reference</h3>
<p>This section describes how to use the <a href="/explore#cards" />"Explore cards"</a> field.</p>
<p>The simple "language" used to search the card database is based on the query language used by <a href="http://magiccards.info/syntax.html">magiccards.info</a> and <a href="https://scryfall.com/docs/reference">Scryfall</a>. As a quick comparison to Scryfall (which has slightly more feature that magiccards.info), these are the main differences:</p>
<ul>
	<li>Features that don't make much sense in relation to custom cards, such as blocks, formats, borders, nicknames, reprints, "funny" etc. are not available.</li>
	<li>OR operator is not available (this will hopefully be improved in the future).</li>
	<li>Several other minor features are not available, such as planeswalker loyalty, color identity, ~ etc.</li>
	<li>You can search using card author, upload date and set status.</li>
</ul>
<h4>Basics</h4>
<p>The search query is composed from terms that are separated by spaces. Each term may include a keyword, such as <code>color:</code> which determinews what attribute of the card the term applies to. If the keyword is not provided, the term will apply to the card's name, types and rules text. These terms are never case sensitive. Unless specified otherwise, all terms must be matched for the card to match the query.</p>
<ul>
	<li><code>legend</code> (cards that include "legend" in their name, types or rules text)</li>
	<li><code>bolt color:red</code> (red cards that include "bolt" in their name, types or rules text)</li>
</ul>
<p>Terms that include spaces need to be wrapped in double quotes (otherwise they will be considered multiple terms):</p>
<ul>
	<li><code>"deals 3 damage to target creature"</code> (cards that say "deals 3 damage to target creature" in their name, types or rules text. If this term wasn't wrapped in quotes, it would also find cards that say for example "deals 3 damage to target player. Creatures you control gain trample until end of turn.")</li>
</ul>
<p><code>!</code> operator can be used either as prefix (exact name match) or infix (exact attribute match):
<ul>
	<li><code>!"lightning bolt"</code> (cards named exactly "lightning bolt")</li>
	<li><code>color!redblack</code> (cards that are both red and black and no other colors)</li>
</ul> 
<p>With some keywords that represent numeric attributes such as "toughness", you can also use numeric comparison operators <code>&lt;</code>, <code>&lt;=</code>, <code>&gt;</code> and <code>&gt;=</code>. You can generally use operator <code>=</code> instead of <code>:</code> (they are treated identically). With most keywords, you can use the <code>!=</code> meaning "not equals to".</p>
<h4>Negating terms</h4>
<p>Prefixing a term with <code>-</code> will match all cards that DO NOT match the term:</p>
<li><code>color:blue -color:red</code> (blue cards that are not red)</li>
<h4>Colors</h4>
<p>You can find cards that include a particular color using <code>c:</code> or <code>color:</code> followed by a full color name or a single letter. <code>colorless</code> or <code>c</code> and <code>multicolor</code> or <code>m</code> are also supported.</p>
<p>This color includes all the colors in the mana cost if not specified explicitly by a color indicator (in which case the color is determined by the color indicator).
<p>Examples:</p>
<ul>
	<li><code>c:rg</code> (cards that are both red and green)</li>
	<li><code>c!rug</code> (exactly temur creatures)</li>
	<li><code>c:bluewhite</code> (cards that are both blue and white)</li>
	<li><code>c:mu</code> (multicolored cards that include blue)</li>
	<li><code>t:warrior c:r -c:g</code> (red warriors that are not green)</li>
</ul>
<p>Order of colors doesn't matter, even when the exact match operator (<code>!</code>) is used.</p>
<h4>Card types</h4>
<p>You can use <code>t:</code> or <code>types:</code> followed by a string to find cards including particular type (or types) on their type line. If you use a string with multiple words, these words have to appear on the card in the exact order in which they are on the card.</p>
<p>Examples:</p>
<ul>
	<li><code>t:farie</code> (cards that include "faerie" on their type line)</li>
	<li><code>t:"legendary creature"</code> (cards that include "legendary artifact" on their type line, but doesn't match "legendary artifact creature")</li>
	<li><code>t:"creature legendary"</code> (doesn't find any cards - "legendary" always comes before "creature" on the type line)</li>
	<li><code>t:creature t:legendary</code> (cards that include both "creature" and "legendary" somewhere on their type line, so it matches "legendary artifact creature" unlike the examples above)</li>
</ul>
<p>There are also shortcut classification terms <code>is:spell</code> and <code>is:permanent</code> that match the appropriate card types. <code>is:token</code> also works.</p>
<h4>Rules text</h4>
<p>You can use <code>o:</code> or <code>oracle:</code> or <code>rules:</code> or <code>text:</code> or <code>rt:</code> followed by a string to find cards including that string in their rules text.</p>
<p>Examples:</p>
<ul>
	<li><code>text:"you win the game"</code> (cards that say "you win the game" in their rules text)</li>
	<li><code>o:draw type:creature</code> (creatures that deal with drawing cards)</li>
	<li><code>o! type:creature -type:token</code> (completely vanilla nontoken creatures)</li>
</ul>
<p>There is also a shortcut term <code>is:etb</code> for cards that include "enters the battlefield" in their rules text.</p>
<p>Note that automatic replacement of "~" with the card's name is not supported.</p>

<h4>Mana costs</h4>
<p>You can use <code>m:</code> or <code>mana:</code> followed by a mana cost to find cards that include specific string in their mana cost. There are three different ways to enter mana costs:</p>
<ul>
	<li>"Naked" syntax - eg. <code>5GG</code>. Hybrid mana symbols can't be entered this way.</li>
	<li>PlaneSculptors syntax with square brackets - eg. <code>[5][G][G]</code>. Hydrid mana symbols are entered as <code>[2U][RG]</code>. Phyrexian mana costs are entered as <code>[PW]</code>. For more information see the <a href="#symbols"/>formatting syntax reference above</a>.</li>
	<li>Scryfall syntax with curly brackets - eg. <code>{5}{G}{G}</code>. Hydrid mana symbols are entered as <code>{2/U}{R/G}</code>. Phyrexian mana costs are entered as <code>{W/P}</code>.</li>
</ul>
<p>These syntaxes can be liberally combined even in a single term.</p>
<p>Order of the symbols matters.</p>
<p>Examples:</p>
<ul>
	<li><code>m:2[2U]</code> (cards that have a <span class="icon-wrapper"><i class="mtg mana-2"></i></span> followed by a <span class="icon-wrapper"><i class="mtg hybrid-2u"></i></span>&nbsp;&nbsp;in their mana cost)</li>
	<li><code>m!WW</code> (cards that cost exactly <span class="icon-wrapper"><i class="mtg white"></i></span><span class="icon-wrapper"><i class="mtg white"></i></span>)</li>
</ul>
<p>You can also use <code>cmc:</code> to find cards with specified mana costs. Arithmetic comparison operators are supported.</p>
<ul>
	<li><code>c:u cmc:2 type:creature</code> (mono-blue two-drop creatures)</li>
	<li><code>cmc>7 is:spell</code> (spells that cost more than 7 mana)</li>
</ul>

<h4>Power and toughness</h4>
<p>You can use <code>pow:</code> or <code>power:</code> and <code>tou:</code> or <code>toughness:</code> to find cards with specific mana costs. Arithmetic comparison operators are supported. You can also compare power and toughness to each other (but not to other attributes).</p>
<p>Examples:</p>
<ul>
	<li><code>cmc&lt;3 pow&gt;3</code> (cards that have power greater than 3 but cost less than 3 mana)</li>
	<li><code>color:black toughness&gt;power</code> (black cards that have toughness greater than power)</li>
</ul>

<h4>Multi-faced cards</h4>
<p>Generally, at least one of a multifaced card's faces must match the search criteria to show up in search results.</p>
<p>You can query card's "shape" using the <code>is:</code> keyword:</p>
<ul>
	<li><code>is:normal</code> (normal single faced cards)</li>
	<li><code>is:dfc</code> or <code>is:transform</code> (double faced cards)</li>
	<li><code>is:split</code> (split cards including fuse cards)</li>
	<li><code>is:flip</code> (flip cards)</li>
</ul>

<h4>Rarity</h4>
<p>You can use <code>r:</code> or <code>rarity:</code> to find cards with specific rarity. Use either full name ("common", "uncommon", "rare", "mythic" or "special") or a single letter shorthand:</p>
<p>Examples:</p>
<ul>
	<li><code>r:m c:r t:dragon</code> (mythic red dragons)</li>
	<li><code>r:c c:blue is:spell text:"draw a card"</code> (common blue cantrips)</li>
</ul>

<h4>Sets, set statuses and authors</h4>
<p>You can use <code>s:</code> or <code>set:</code> or <code>e:</code> or <code>edition:</code> to find cards from specific sets. To specify a set, you can use either a part of its name, part of its URL name or a part of its code.</p>
<p>You can also chain multiple sets using either <code>+</code> (cards that appeared in all of the chained sets) or <code>|</code> (cards that appeared in at least one of the chained sets).</p>
<p>Examples:</p>
<ul>
	<li><code>s:aenyr c:g cmc:2</code> (green two drops from Aenyr)</li>
	<li><code>s:aenyr|dreamscape</code> (card that appeared either in Aenyr or in Dreamscape)</li>
</ul>
<p>You can use <code>st:</code> or <code>status:</code> to find cards from sets that are in specified status. Valid values are "unplayable"/"un", "design", "development"/"dev", "finishing" and "finished"/"done". You can use arithmetic comparison operators with these values.</p>
<p>Discontinued sets are not matched unless you specifically ask for them with <code>st:discontinued</code> or <code>st:dis</code>.</p>
<p>Additionally, you can use <code>st:play</code> or <code>st:playable</code> to find cards from sets that are not in statuses "unplayable and "discontinued".</p>
<ul>
	<li><code>st:finished r:m</code> (all mythics from finished sets)</li>
</ul>
<p>You can use <code>au:</code> or <code>author:</code> to find cards from sets made by specific author. The author can be specified using either their user name or their URL name:</p>
<ul>
	<li><code>r:c au:matej-zabsky</code> (all commons made by me)</li>
</ul>

<h4>Artist and rules text</h4>
<p>You can use <code>a:</code> or <code>art:</code> or <code>artist:</code> to find cards with art by specific artists (as specified in the card's footer):</p>
<ul>
	<li><code>art:"Noah Bradley" t:land</code> (all lands illustrated by Noah Bradley)</li>
</ul>
<p>You can also use <code>f:</code> or <code>ft:</code> or <code>flavor:</code> to find cards with specific string in their flavor text:</p>
<ul>
	<li><code>flavor:"Keiaraq"</code> (all cards with "Keiaraq" in their flavor text)</li>
	<li><code>flavor!</code> (all cards without a flavor text)</li>
</ul>
<h4>Unrolling searches, upload dates</h4>
<p>By default, only cards from the newest version of each set are searched. However, unlike in Scryfall, a card can be matched multiple times if it appears in multiple sets (even if it is exactly the same).</p>
<p>You can unroll the search by prefixing it with <code>++</code>, which will cause all versions of all cards to be searched.</p>
<ul>
	<li><code>++!"Deepmind Mori"</code> (all versions of a card named "Deepmind Mori")</li>
</ul>
<p>You can also restrict the cards matched by date when they were uploaded to the site using <code>date:</code> keyword. You should use arithmetic comparison operators with date (exact matches make little sense). Note that if you use this keyword without unrolling the search using <code>++</code>, only cards from sets that were last updated during matching time interval will be matched.</p>
<p>Date can be specified either in "YYYY-MM-DD" format or intuitively such as "yesterday", "-3weeks" (for details see <a href="http://php.net/manual/en/function.strtotime.php">strtotime PHP function</a>). Note that if you specify a date this way, the exact moment specified is 00:00 of that day.</p>
<ul>
	<li><code>++date>-1week</code> (all cards uploaded in last 7 days)</li>
</ul>
<p>For technical reasons, only versions of cards uploaded after 29th September of 2016 are searched (images from set versions older than that are stored off-site and are mostly broken).</p>
<a name="set-import"></a>
<h3 id="contentTitle">How to import sets into PlaneSculptors</h3>
<div class="tutorial">
<p>This tutorial assumes you created your custom set using <a href="http://magicseteditor.sourceforge.net/">Magic Set Editor 2</a>.</p>
<ol>
	<li><strong>Export card data file for WebDrafter</strong>
		<ol>
			<li>Download <a href="/download/magic-planesculptors.mse-export-template.zip">WebDrafter export template</a> for MSE.</li>
			<li>Extract the archive into the "data" directory in the location where MSE2 is installed. Restart MSE, if it was running.</li>
			<li>In MSE, go to "File"->"Export"->"HTML". Click OK and choose an export location. <br /><img src="http://puu.sh/qsHw8/64bb443327.png" /></li>
	
		</ol>
	</li>
	<li><strong>Export card images</strong>
		<ol>
			<li>In MSE, go to "File"->"Export"->"All card images".</li>
			<li>If you want, you can change the file extension to .png for improved image quality (but bigger image files). <br /><img src="http://puu.sh/j3SOd/d5afb1ec01.png"></li>
			<li>Click OK and choose a directory where the files will be exported.</li>
		</ol>
	</li>
	<li><strong>Publish card images on Google Drive</strong>
		<ol>
			<li>If you don't have Google account, <a href="https://accounts.google.com/signup?hl=cs">create one</a>. It is completely free.</li>
			<li>Download and install <a href="https://www.google.com/intl/cs_cz/drive/download/">Google Drive</a> application on your computer.</li>
			<li>Open File Explorer and go to Google Drive (it should be in the Favorites section in the left panel, if you have recent version of Windows). If you can't find it, go to tray bar (on bottom left of the screen, just next of the clock) and look for a Google Drive icon (a green-yellow-blue triangle), click it and click "Open Google Drive folder".</li>
			<li>Create a folder where you will put the card images. I recommend to have a nice folder structure, something like "Custom Sets/Khans of Tarkir/Khans of Tarkir 1.0". It is a very good idea to keep older versions of the set intact, so that WebDrafter can keep older drafts in its archive.</li>
			<li>Right click the folder in Windows Explorer and in the context menu go to Google Drive -> Share... . In the window that opens go to Advanced and make sure "Who has access" includes "Everyone - public on web".</li>
			<li>Copy the card images into the prepared folder. Next time, you can have MSE generate the card images straight onto the Google Drive.</li>
			<li>Wait until Google Drive uploads the images into the cloud. You can see the synchronization status when you click on the Google Drive icon in the tray bar. <br /><img src="http://puu.sh/j3TU7/47cd2a5137.png" /></li>
		</ol>
	</li>
	<li><strong>Import the set into PlaneSculptors</strong>
		<ol>
			<li>Go the the <a href="<?php echo $this->url('home')?>">main page of PlaneSculptors</a>.</li>
			<li>Click "login". You will be redirected to a Google page. If you are not yet logged into Google, log in. Then authorize PlaneSculptors. You will be redirected back to the application, the the main page of the member area.</li>
			<li>Click create set.</li>
			<li>Fill in set name (the name must be unique across all registered sets) and set code (that doesn't have to be unique).</li>
			<li>Your set was created. Now go to "Upload card file" tab.</li> 
			<li>Depending on your card image format, choose appropriate option in "Art file name format".</li>
			<li>Add the set files and all the image files to the uploader. You can either click it and select all the files in the popup window or you can drag and drop them into the uploader area. I prefer to export the set file into the same directory as all the images, so that I can just click the uploader, navigate to the directory where all the files are and hit "Ctrl+A" to select all the files.</li>
			<li>Click "Proceed". The importer will now check if there are any errors in the import file and then will redirect you to the next stage.</li>
			<li>If you have created a Cockatrice package, upload it to some place on the internet and put the link into "Download URL".</li>
			<li>Click "Submit". You will be directed back to the set management page.</li>
			<li>Your set now has cards. If you want the set to be playable, go to "Development stage" tab and select an appropriate option.</li>
			<li>You can also make a beautiful home page for your set on the "Set details" tab.</li>
			<li>If you want the set to become publicly listed on the website, click "Make public". Make sure that the set reflects well on you and the custom magic community as a whole. Please don't make effortless dreck public. You can still host events with your private sets.</li>
			<li>You can now host events with your set!</li>
		</ol>
	</li>
</ol>
</div>