<h2 id="contentTitle">How to import sets into WebDrafter</h2>
<div class="tutorial">
This tutorial assumes you created your custom set using <a href="http://magicseteditor.sourceforge.net/">Magic Set Editor 2</a>.

<ol>
	<li><strong>Export card data file for WebDrafter</strong>
		<ol>
			<li>Download <a href="http://puu.sh/i8GMt/28e82db942.zip">WebDrafter export template</a> for MSE.</li>
			<li>Extract the archive into the "data" directory in the location where MSE2 is installed. Restart MSE, if it was running.</li>
			<li>In MSE, go to "File"->"Export"->"HTML". Click OK and choose an export location. <br /><img src="http://puu.sh/j3Swk/329dda2e6c.png" />
	
		</ol>
	</li>
	<li><strong>Export card images</strong>
		<ol>
			<li>In MSE, go to "File"->"Export"->"All card images".</li>
			<li>If you want, you can change the file extension to .png for improved image quality (but bigger image files). <br /><img src="http://puu.sh/j3SOd/d5afb1ec01.png">
			<li>Click OK and choose a directory where the files will be exported.
		</ol>
	</li>
	<li><strong>Publish card images on Google Drive</strong>
		<ol>
			<li>If you don't have Google account, <a href="https://accounts.google.com/signup?hl=cs">create one</a>. It is completely free.</li>
			<li>Download and install <a href="https://www.google.com/intl/cs_cz/drive/download/">Google Drive</a> application on your computer.</li>
			<li>Open File Explorer and go to Google Drive (it should be in the Favorites section in the left panel, if you have recent version of Windows). If you can't find it, go to tray bar (on bottom left of the screen, just next of the clock) and look for a Google Drive icon (a green-yellow-blue triangle), click it and click "Open Google Drive folder".
			<li>Create a folder where you will put the card images. I recommend to have a nice folder structure, something like "Custom Sets/Khans of Tarkir/Khans of Tarkir 1.0". It is a very good idea to keep older versions of the set intact, so that WebDrafter can keep older drafts in its archive.
			<li>Copy the card images into the prepared folder. Next time, you can have MSE generate the card images straight onto the Google Drive.
			<li>Wait until Google Drive uploads the images into the cloud. You can see the synchronization status when you click on the Google Drive icon in the tray bar. <br /><img src="http://puu.sh/j3TU7/47cd2a5137.png" />
		</ol>
	</li>
	<li><strong>Import the set into WebDrafter</strong>
		<ol>
			<li>Go the the <a href="http://webdrafter.geogen.cz">main page of WebDrafter</a>.
			<li>Click "login". You will be redirected to a Google page. If you are not yet logged into Google, log in. Then authorize WebDrafter. You will be redirected back to the application, the the main page of the member area.
			<li>Click create set.
			<li>Fill in set name (the name must be unique across all registered sets, this includes retired sets. I recomment to include version number or date) and set code (that doesn't have to be unique). 
			<li>Optionally, you can fill in "Information URL". This should contain a link to the set's web page (if it has any) or related discussion thread - simply a location where curious players can find additional information about the set.
			<li>Click the "Pick from Google Drive" button. A window opens with the contents of your Google Drive. Choose the folder where your card images are located and click "Select". <br /><img src="http://puu.sh/j3UsN/b520be0d4f.png">.
			<li>Depending on your card image format, choose appropriate option in "Art file name format".
			<li>If you have create a Cockatrice package, upload it to some place on the internet and put the link into "Download URL".
			<li>Click "Choose file", find your set export file, and click OK. 
			<li>Click "Create".
			<li>You should now be back on the main page of the member area and the application should be informing you "Set create". You should be able to see the set in the list of "Sets you created". You can click the set name to inspect it or go straight to hosting an event with it!
			<li>If you created the set, but something is wrong, go the member area, and click "Retire" next to the set name. This will remove the set from all listings, but will keep any events that used it intact.
		</ol>
	</li>
</ol>
