<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_deck version="1">
    <deckname><?php echo $this->deckName?></deckname>
    <comments>Created by PlaneSculptors</comments>
    <zone name="main">
<?php
foreach ($this->maindeck as $card => $count)
{
	echo '        <card number="' .$count . '" price="0" name="' . $card . '"/>' . "\n";
}
?>
    </zone>
    <zone name="sideboard">
<?php
foreach ($this->sideboard as $card => $count)
{
	echo '        <card number="' .$count . '" price="0" name="' . $card . '"/>' . "\n";
}
?>
		<card number="25" price="0" name="Plains"/>
		<card number="25" price="0" name="Island"/>
		<card number="25" price="0" name="Swamp"/>
		<card number="25" price="0" name="Mountain"/>
		<card number="25" price="0" name="Forest"/>
    </zone>
</cockatrice_deck>