<?php
function replaceBotSymbols($str){
	$str = str_replace("[X]", ":X_: ", $str);
	$str = str_replace("[0]", ":0_: ", $str);
	$str = str_replace("[1]", ":1_: ", $str);
	$str = str_replace("[2]", ":2_: ", $str);
	$str = str_replace("[3]", ":3_: ", $str);
	$str = str_replace("[4]", ":4_: ", $str);
	$str = str_replace("[5]", ":5_: ", $str);
	$str = str_replace("[6]", ":6_: ", $str);
	$str = str_replace("[7]", ":7_: ", $str);
	$str = str_replace("[8]", ":8_: ", $str);
	$str = str_replace("[9]", ":9_: ", $str);
	$str = str_replace("[10]", ":10: ", $str);
	$str = str_replace("[11]", ":11: ", $str);
	$str = str_replace("[12]", ":12: ", $str);
	$str = str_replace("[13]", ":13: ", $str);
	$str = str_replace("[14]", ":14: ", $str);
	$str = str_replace("[15]", ":15: ", $str);
	$str = str_replace("[S]", ":S_: ", $str);
	$str = str_replace("[T]", ":T_: ", $str);
	$str = str_replace("[Q]", ":Q_: ", $str);
	$str = str_replace("[E]", ":E_: ", $str);
	
	
	$str = str_replace("[W]", ":W_: ", $str);
	$str = str_replace("[U]", ":U_: ", $str);
	$str = str_replace("[B]", ":B_: ", $str);
	$str = str_replace("[R]", ":R_: ", $str);
	$str = str_replace("[G]", ":G_: ", $str);
	
	$str = str_replace("[PW]", ":PW: ", $str);
	$str = str_replace("[PU]", ":PU: ", $str);
	$str = str_replace("[PB]", ":PB: ", $str);
	$str = str_replace("[PR]", ":PR: ", $str);
	$str = str_replace("[PG]", ":PG: ", $str);
 	
	$str = str_replace("[WU]", ":WU: ", $str);
	$str = str_replace("[UB]", ":UB: ", $str);
	$str = str_replace("[BR]", ":BR: ", $str);
	$str = str_replace("[RG]", ":RG: ", $str);
	$str = str_replace("[GW]", ":GW: ", $str);

	$str = str_replace("[WB]", ":WB: ", $str);
	$str = str_replace("[BG]", ":BG: ", $str);
	$str = str_replace("[GU]", ":GU: ", $str);
	$str = str_replace("[UR]", ":UR: ", $str);
	$str = str_replace("[RW]", ":RW: ", $str);
	
	return $str;
}

if(isset($this->message)){
	echo $this->message;
	return;
}

foreach($cards as $i => $card){
	if($i == 3){
		echo "**More than three matching cards were found. Please narrow down your search.**";
		return;
	}
	
	//var_dump($card);

	
	$rulesText = null;
	if ($card->rulesText != null) {
		$rulesText = str_replace("<i>", "*", replaceBotSymbols(html_entity_decode($card->rulesText)));
		$rulesText = str_replace("</i>", "*", $rulesText);
		$rulesText = str_replace("<b>", "**", $rulesText);
		$rulesText = str_replace("</b>", "**", $rulesText);
		$rulesText = str_replace("<br />", "", $rulesText);
		$rulesText = str_replace("<br/>", "", $rulesText);
		$rulesText = str_replace("<br>", "", $rulesText);;
		$rulesText = str_replace("<span class=\"symbol\">", "", $rulesText);;
		$rulesText = str_replace("</span>", "", $rulesText);;
		//$rulesText = str_replace("\\n", "\n", $rulesText);
	}
	
	$flavorText = null;
	if ($card->flavorText != null) {
		$flavorText = str_replace("<i>", "*", html_entity_decode($card->flavorText));
		$flavorText = str_replace("</i>", "*", $flavorText);
		$flavorText = str_replace("<b>", "**", $flavorText);
		$flavorText = str_replace("</b>", "**", $flavorText);
		$flavorText = str_replace("<br />", "", $flavorText);
		$flavorText = str_replace("<br/>", "", $flavorText);
		$flavorText = str_replace("<br>", "", $flavorText);
		$flavorText = str_replace("<span class=\"symbol\">", "", $flavorText);;
		$flavorText = str_replace("</span>", "", $flavorText);;
	}
	
	$rulesText2 = null;
	$flavorText2 = null;
	if($card->getShapeName() != "normal")
	{
		if ($card->rulesText2 != null) {
			$rulesText2 = str_replace("<i>", "*", replaceBotSymbols(html_entity_decode($card->rulesText2)));
			$rulesText2 = str_replace("</i>", "*", $rulesText2);
			$rulesText2 = str_replace("<b>", "**", $rulesText2);
			$rulesText2 = str_replace("</b>", "**", $rulesText2);
			$rulesText2 = str_replace("<br />", "", $rulesText2);
			$rulesText2 = str_replace("<br/>", "", $rulesText2);
			$rulesText2 = str_replace("<br>", "", $rulesText2);
			$rulesText2 = str_replace("<span class=\"symbol\">", "", $rulesText2);;
			$rulesText2 = str_replace("</span>", "", $rulesText2);;
		}
	
		if ($card->flavorText2 != null) {
			$flavorText2 = str_replace("<i>", "*", html_entity_decode($card->flavorText2));
			$flavorText2 = str_replace("</i>", "*", $flavorText2);
			$flavorText2 = str_replace("<b>", "**", $flavorText2);
			$flavorText2 = str_replace("</b>", "**", $flavorText2);
			$flavorText2 = str_replace("<br />", "", $flavorText2);
			$flavorText2 = str_replace("<br/>", "", $flavorText2);
			$flavorText2 = str_replace("<br>", "", $flavorText2);
			$flavorText2 = str_replace("<span class=\"symbol\">", "", $flavorText2);;
			$flavorText2 = str_replace("</span>", "", $flavorText2);;
		}
	}
	?><?php 
	$cardCode = 
	'**' . $card->name . "**\t" . replaceBotSymbols($card->manaCost) . "\n" .
	$card->types . "\t" . ($this->set !== null ? $this->set->name : $card->setName) . " (" . $card->rarity . ")\n" .
	($rulesText != null ? $rulesText . "\n" : "") .
	($flavorText != null ? $flavorText . "\n" : "") .
	($card->ptString != null ? $card->ptString . "\n" : "") .
	($card->shape == \Application\Model\Card::SHAPE_NORMAL ? "" : (
		"///\n".
		'**' . $card->name2 . "**\t" . replaceBotSymbols($card->manaCost2) . "\n" .
		$card->types2 . "\n" .
		($rulesText2 != null ? $rulesText2 . "\n" : "") .
		($flavorText2 != null ? $flavorText2 . "\n" : "") .
		($card->ptString2 != null ? $card->ptString2 . "\n" : "")
	)) . (@substr($card->artUrl, 0, 1) == '/' ? 'http://www.planesculptors.net' : '') . $card->artUrl;
	
	$cardCode = str_replace("\\n", '\n', $cardCode);
	$cardCode = str_replace("\n\n", '\n', $cardCode);
	
	echo $cardCode . "\n\n";
}
?>