<?php $this->headTitle()->append($this->card->name); 

if($this->changeHistory != NULL)
{
	$modifiedChangeHistory = $this->changeHistory;
	
	if($modifiedChangeHistory[0]->cardId == $this->card->cardId)
	{
		array_shift ($modifiedChangeHistory); // Remove the first entry of the history, if it is the "current" card
	}
	
	?>
	<script>
	var spoiler;
	var historyData = <?php echo $this->partial(
		'/application/fragment/cards-to-spoiler-data', 
		array(
			'set' => $this->set,
			'setVersion' => null,
			'cards' => $modifiedChangeHistory
	)); 
	?>

	$(function(){
		spoiler = new Spoiler({element: $("#change-history"), data: historyData, enableControl: false, showVersion: true});
	});
	
	
	</script>
<?php }?>
<script>
var bbCode = '<?php echo $this->partial('/application/fragment/card-to-phpbb', array('setUrlName' => $this->set->urlName, 'versionUrlName' => $this->setVersion->urlName, 'card' => $card)) ?>';
</script>
<h2 id="contentTitle"><?php echo $this->card->name; ?></h2>
<div id="card-page">
	<div class="info-bar">
		<span class="info-bar-item">Author: <a href="<?php echo $this->url('browse-user', array('url_name' => $this->user->urlName)) ?>"><?php echo $this->user->name ?></a></span>		
		<span class="info-bar-item">Set: <a href="<?php echo $this->url('browse-set', array('url_name' => $this->set->urlName)) ?>"><?php echo $this->set->name ?></a></span>
		<span class="info-bar-item">Version: <a href="<?php echo $this->url('browse-version', array('url_name' => $this->set->urlName, 'version_url_name' => $this->setVersion->urlName)) ?>"><?php echo $this->setVersion->name ?></a></span>		
		<span class="info-bar-item">Stage: <span class="set-status-label set-status-label-<?php echo $this->set->status ?>"><?php echo $this->set->getStatusName() ?></span></span>		
		<span class="info-bar-item">Privacy: <?php echo $this->set->isPrivate ? "Private" : "Public"?></span>
		<span class="info-bar-item">Last changed: <?php echo $this->card->changedOn?></span>
		<span class="info-bar-item"><a href="#" onclick="showCopyable('<?php echo $this->card->artUrl?>')">Copy image link</a></span>
		<span class="info-bar-item"><a href="#" onclick="showCopyable(bbCode)">Copy forum code</a></span>
	</div>
	<table class="card-detail shape-<?php echo $this->card->getShapeName() ?>">
		<tbody>
			<tr>
				<td class="card-image-day card-front" rowspan="15">
					<div style="background-image: url(&quot;<?php echo $this->card->artUrl ?>&quot;)"></div>
				</td>
				<?php if($this->card->shape == \Application\Model\Card::SHAPE_FLIP || $this->card->shape == \Application\Model\Card::SHAPE_DOUBLE){ ?>
					<td class="card-image-night card-front" rowspan="15">
						<div style="background-image: url(&quot;<?php echo $this->card->artUrl ?>&quot;)"></div>
					</td>
				<?php } ?>
				<td class="card-main-row card-front">
					<div class="card-name"><?php echo $this->card->name ?></div>
					<div class="card-cost">
						<?php echo $this->symbols($this->card->manaCost) ?>
					</div>
				</td>
			</tr>
			<tr>
				<td class="card-type-row card-front">
					<div class="card-types"><?php echo $this->card->types ?></div>
					<div class="card-rarity card-rarity-<?php echo strtolower($this->card->rarity) ?>"><?php echo $this->card->getRarityName() ?></div>
				</td>
			</tr>
			<tr>
				<td class="card-rules-row card-front">
					<div class="card-rules"><?php echo $this->symbols($this->card->rulesText) ?></div>
				</td>
			</tr>
			<tr>
				<td class="card-flavor-row card-front">
					<div class="card-flavor"><?php echo $this->card->flavorText ?></div>
				</td>
			</tr>
			<tr>
				<td class="card-pt-row card-front">
					<div class="card-pt"><?php echo $this->card->ptString ?></div>
				</td>
			</tr>
			<tr>
				<td class="card-filler-row card-front">
					&nbsp;
				</td>
			</tr>
			<?php if($this->card->shape != \Application\Model\Card::SHAPE_NORMAL){ ?>
				<tr>
					<td class="card-separator"><hr/></td>
				</tr>
				<tr>
					<td class="card-main-row card-back">
						<div class="card-name"><?php echo $this->card->name2 ?></div>
						<div class="card-cost">
							<?php echo $this->symbols($this->card->manaCost2) ?>
						</div>
					</td
				</tr>
				<tr>
					<td class="card-type-row card-back">
						<div class="card-types"><?php echo $this->card->types2 ?></div>
						<div class="card-rarity card-rarity-<?php echo strtolower($this->card->rarity) ?>"><?php echo $this->card->getRarityName() ?></div>
					</td>
				</tr>
				<tr>
					<td class="card-rules-row card-back">
						<div class="card-rules"><?php echo $this->symbols($this->card->rulesText2) ?></div>
					</td>
				</tr>
				<tr>
					<td class="card-flavor-row card-back">
						<div class="card-flavor"><?php echo $this->card->flavorText2 ?></div>
					</td>
				</tr>
				<tr>
					<td class="card-pt-row card-back">
						<div class="card-pt"><?php echo $this->card->ptString2 ?></div>
					</td>
				</tr>
				<tr>
					<td class="card-filler-row">
						&nbsp;
					</td>
				</tr>
			<?php } ?>
		</tbody>
	</table>
	<?php if($this->changeHistory != NULL) {?>	
		<h2>Change history</h2>
		<div id="change-history"></div>
	<?php } ?>
</div>