<?php $this->headTitle()->append("Explore content"); ?>
<script>
$(function(){
	makeTabs($("#tabs"));
	
	$('#sets-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});
	
	/*$('#cards_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});*/
	
	$('#users-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});

	$('.dataTable').on( 'click', 'tr', function () {
		$(this).addClass('selected');
		if($(this).attr('url') != null)
		{
			window.location = $(this).attr('url');
		}
	});

	$(".lazyload").lazyload({
	});
});
</script>

<h2 id="contentTitle">Explore content</h2>
<div id="tabs">
	<ul>
		<li><a href="#sets">Sets</a></li>
		<li><a href="#cards">Cards</a></li>
		<li><a href="#users">Users</a></li>
	</ul>
	<div id="sets">
		<table id="sets-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>Set name</th>
					<th>Stage</th>
					<th>Author</th>
					<th>Date</th>
					<th>Number of cards</th>
					<th>Number of events</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->sets as $set)
		{
			echo "<tr url='" . $this->url('browse-set', array('url_name' => $set["urlName"])) . "'><td class='nameCell'>";
			echo $set["setName"];
			echo "</td><td>";
			echo "	<span class='set-status-label set-status-label-" . $set["setStatus"] ."'>" . \Application\Model\Set::getStatusNameStatic($set["setStatus"]) . "</span>";
			echo "</td><td>";
			echo $set["userName"];
			echo "</td><td>";
			echo $set["createdOn"];
			echo "</td><td>" . $set["cardCount"] . "</td><td>" . $set["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="cards">
		<form action="#cards"><input name="query" type="text" value="<?php echo $this->query?>" /><input type="submit" /></form>
		<div id='spoiler'>
			<div class='spoiler-cards'>
			<?php if($this->cards != NULL){
				foreach($this->cards as $card){
					?>
					<img class='lazyload' data-original="<?php echo $card->art_url ?>" alt="<?php echo $card->name ?>" class='card-image card-image-<?php echo $card->shape ?>' />
					<?php
				}
			}?>
			</div>
		</div>
	</div>
	<div id="users">
		<table id="users-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>User name</th>
					<th>Number of sets</th>
					<th>Number of events played</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->users as $user)
		{
			echo "<tr url='" . $this->url('browse-user', array('url_name' => $user["userUrlName"])) . "'><td class='nameCell'>";
			echo $user["userName"];
			echo "</td><td>" . $user["setCount"] . "</td><td>" . $user["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
</div>