<script>
$(function(){
	$("#tabs").tabs();
	
	$('#sets_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});
	
	/*$('#cards_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});*/
	
	$('#users_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});

	$('.dataTable').on( 'click', 'tr', function () {
		$(this).addClass('selected');
		window.location = $(this).attr('url');
	});
});
</script>

<h2 id="contentTitle">Explore content</h2>
<div id="tabs">
	<ul>
		<li><a href="#sets_tab">Sets</a></li>
		<li><a href="#cards_tab">Cards</a></li>
		<li><a href="#users_tab">Users</a></li>
	</ul>
	<div id="sets_tab">
		<table id="sets_grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>Set name</th>
					<th>Author</th>
					<th>Date</th>
					<th>Number of cards</th>
					<th>Number of events</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->sets as $set)
		{
			echo "<tr url='" . $this->url('browse-set', array('set_id' => $set["setId"])) . "'><td class='nameCell'>";
			echo $set["setName"];
			echo "</td><td>";
			echo $set["userName"];
			echo "</td><td>";
			echo $set["createdOn"];
			echo "</td><td>" . $set["cardCount"] . "</td><td>" . $set["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="cards_tab">
		WIP
	</div>
	<div id="users_tab">
		<table id="users_grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>User name</th>
					<th>Number of sets</th>
					<th>Number of events played</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->users as $user)
		{
			echo "<tr url='" . $this->url('browse-user', array('user_id' => $user["userId"])) . "'><td class='nameCell'>";
			echo $user["userName"];
			echo "</td><td>" . $user["setCount"] . "</td><td>" . $user["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
</div>