<?php $this->headTitle()->append("Explore content"); ?>
<script>
$(function(){
	makeTabs($("#tabs"));
	
	$('#sets-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 10000
	});
	
	/*$('#cards_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});*/
	
	$('#users-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"paging": false,
		"info": false
	});

	$('.dataTable').on( 'click', 'tr', function () {
		$(this).addClass('selected');
		if($(this).attr('url') != null)
		{
			window.location = $(this).attr('url');
		}
	});
	
	$(".lazyload").lazyload({
		effect : "fadeIn",
		threshold : 200
	});
	
	/*$(document).tooltip({
		items: ".card-image",
		track: true,
		show: false,
		hide: false,
		content: function(){
			var element = $(this);
			return "<img src='" + element.attr("src") + "' class='tooltip-card'>";
		}
	});*/
	
	$( "#tabs" ).on( "tabsactivate", function( event, ui ) {
		if(ui.newPanel.attr('id') == "cards"){
			$(window).trigger('resize'); // Refresh lazyload
		}
	} );

	
});
</script>

<h2 id="contentTitle">Explore content</h2>
<div id="tabs">
	<ul>
		<li><a href="#sets">Sets</a></li>
		<li><a href="#cards">Cards</a></li>
		<li><a href="#users">Users</a></li>
	</ul>
	<div id="sets">
		<table id="sets-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>Set name</th>
					<th>Stage</th>
					<th>Author</th>
					<th>Date</th>
					<th>Number of cards</th>
					<th>Number of events</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->sets as $set)
		{
			echo "<tr url='" . $this->url('browse-set', array('url_name' => $set["urlName"])) . "'><td class='nameCell'>";
			echo $set["setName"];
			echo "</td><td>";
			echo "	<span class='set-status-label set-status-label-" . $set["setStatus"] ."'>" . \Application\Model\Set::getStatusNameStatic($set["setStatus"]) . "</span>";
			echo "</td><td>";
			echo $set["userName"];
			echo "</td><td>";
			echo $set["createdOn"];
			echo "</td><td>" . $set["cardCount"] . "</td><td>" . $set["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="cards">
		<form action="#cards">
			<p>Search query: <span class="query-help"><a href="<?php echo $this->url('tutorial') ?>#querying"/>(Query syntax reference)</a></span></p>
			<input name="query" type="text" value="<?php echo htmlspecialchars($this->query)?>" id="query-input" /><br />
			<input type="submit" value="Search" />
		</form>
		<?php if(count($this->messages) > 0){?>
		<ul class="error-list">
			<?php foreach($this->messages as $message){?>
				<li><?php echo $message ?></li>
			<?php } ?>
		</ul>
		<?php } else if($this->cards != null) { ?>
		<div id='spoiler'>
			<div class='spoiler-cards query-results'>
			<p>Found <?php echo count($this->cards)?> cards.</p>
			<?php if($this->cards != NULL){
				foreach($this->cards as $card){
					?>
					<a href="<?php echo $this->url("browse-card", array('set_url_name' => $card->set_url_name, 'version_url_name' => $card->version_url_name, 'card_url_name' => $card->url_name))?>" title="<?php echo $card->name ?>"><img class='lazyload card-image card-image-<?php echo \Application\Model\Card::getShapeNameStatic($card->shape) ?>' data-original="<?php echo $card->art_url ?>" alt="<?php echo $card->name ?>" height="300"/></a>
					<?php
				}
			}?>
			</div>
		</div>
		<?php } ?>
	</div>
	<div id="users">
		<table id="users-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>User name</th>
					<th>Number of sets</th>
					<th>Number of events played</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->users as $user)
		{
			echo "<tr url='" . $this->url('browse-user', array('url_name' => $user["userUrlName"])) . "'><td class='nameCell'>";
			echo $user["userName"];
			echo "</td><td>" . $user["setCount"] . "</td><td>" . $user["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
</div>