<?php $this->headTitle()->append($this->user->name); ?>
<script>
$(function(){
	$('#owned_sets_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});

	$('#owned_sets_grid tbody').on( 'click', 'tr', function () {
		$(this).addClass('selected');
		if($(this).attr('url') != null)
		{
			window.location = $(this).attr('url');
		}
	});
});
</script>
<h2 id="contentTitle"><?php echo $this->user->name; ?></h2>
<?php 

if(
	($this->auth()->getStatus() == \Application\GoogleAuthentication::STATUS_LOGGED_IN && $this->user->emailPrivacy == \Application\Form\RegistrationForm::EMAIL_PRIVACY_REGISTERED_ONLY) ||
	$this->user->emailPrivacy == \Application\Form\RegistrationForm::EMAIL_PRIVACY_PUBLIC
)
{
	echo "<p>Email: " . $this->user->email . "</p>";
}


$this->markdown($this->user->about) ?>
<table id="owned_sets_grid" class="display hover stripe clickableRows" >
	<thead>
		<tr>
			<th>Set name</th>
			<th>Number of cards</th>
			<th>Number of events</th>
		</tr>
	</thead>
	<tbody>
<?php
		foreach ($this->sets as $set)
		{
			echo "<tr url='" . $this->url('browse-set', array('url_name' => $set["setUrlName"])) . "'><td class='nameCell'>";
			echo $set["setName"];
			echo "</td><td>" . $set["cardCount"] . "</td><td>" . $set["draftCount"] . "</td></tr>";	
		}
?>
		</tr>
	</tbody>
</table>