<script>
$(function(){
	$('#owned_sets_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});

	$('#owned_sets_grid tbody').on( 'click', 'tr', function () {
		$(this).addClass('selected');
		window.location = $(this).attr('url');
	});
});
</script>
<h2 id="contentTitle"><?php echo $this->user->name; ?></h2>
<?php echo \Michelf\Markdown::defaultTransform($this->user->about) ?>
<table id="owned_sets_grid" class="display hover stripe clickableRows" >
	<thead>
		<tr>
			<th>Set name</th>
			<th>Number of cards</th>
			<th>Number of events</th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->sets as $set)
{
	echo "<tr url='" . $this->url('browse-set', array('set_id' => $set->setId)) . "'><td class='nameCell'>";
	echo $set->name;
	echo "</th><td>0</td><td>0</td></tr>";	
}
?>
		</tr>
	</tbody>
</table>