<script>
$(function(){
	$('#owned_sets_grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});
});
</script>
<h2><?php echo $this->user->name; ?></h2>
<?php echo \Michelf\Markdown::defaultTransform($this->user->about) ?>
<table id="owned_sets_grid" class="display hover stripe" >
	<thead>
		<tr>
			<th>Set name</th>
			<th>Number of cards</th>
			<th>Number of events</th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->sets as $set)
{
	echo "<tr><td>";
	echo "<a href='" . $this->url('browse-set', array('set_id' => $set->setId)) . "'>" . $set->name . "</a>";
	echo "</td><td>0</td><td>0</td></tr>";	
}
?>
		</tr>
	</tbody>
</table>