<?php $this->headTitle()->append("New card file for " . $this->set->name); ?>
<script>
var draftStatuses = {"open":1, "running":2, "finished":3};

function updateNeedle(){
	var mode = $("select[name='basic_land_slot']").val();
	var needleNeeded = mode == <?php echo \Application\Model\SetVersion::BASIC_LAND_SLOT_TYPE ?> || mode == <?php echo \Application\Model\SetVersion::BASIC_LAND_SLOT_RULES_TEXT ?>;
	if(needleNeeded){
		$("#basic-land-slot-needle").show();
	}
	else {
		$("#basic-land-slot-needle").hide();
	}
}

$(document).ready(function(){
	var simplemde = createEditor('input[name="about"]');
	$("input[name='submit']").click(function(){ hasUnsavedChanges = false; });

	$("input[name='name']").on('input', function(){
		$("input[name='url_name']").val(toUrlName($(this).val()));
	});

	$("select[name='basic_land_slot']").change(updateNeedle);
	updateNeedle();
});
</script>
<h2 id="contentTitle">New card file for <?php echo $this->set->name ?></h2>
<p>The card file was uploaded and parsed successfully. Please fill in a few more details which will be used to represent this version of the set on PlaneSculptors. During this step, PlaneSculptors will also test whether all card image links work correctly.</p>
<p>Once you submit this form, this version will become the current (and default) version users will see.</p>
<?php
if(count($this->packs) > 0) {
?>
	<p><strong>Custom collation file with <?php echo count($this->packs) ?> packs loaded.</strong></p>
<?php
} 

$form = $this->form;

$form->setAttribute('action', $this->url('member-area-manage-set', array('action' => 'create-set-version', 'set_id' => $this->set->setId), array('query' => array('upload_id' => $this->uploadId)))); 
$form->prepare();

$replacementToken = 'XYZ1234';
$url = $this->url('browse-version', array('url_name' => $this->set->urlName, 'version_url_name' => $replacementToken), array('force_canonical' => true));
$url = substr($url, 0, strpos($url, $replacementToken));

echo $this->form()->openTag($form);
echo $this->fullFormInput($form->get('name'));
echo $this->fullFormInput($form->get('url_name'), $url, null, true);
echo $this->fullFormInput($form->get('download_url'));
echo $this->fullFormInput($form->get('basic_land_slot'), null, '<span id="basic-land-slot-needle"> <span>String to look for: </span>'.$this->formElement($form->get('basic_land_slot_needle')).'</span>');
echo $this->fullFormInput($form->get('about'));
?>
<div class="form_element">
<?php
echo $this->formSubmit($form->get('submit'));
?>
</div>
<?php
echo $this->form()->closeTag();
?>
