<?php $this->headTitle()->append("New card file for " . $this->set->name); ?>
<script>
var draftStatuses = {"open":1, "running":2, "finished":3};

var numRemainingImages;
var numSucceededImages;
var numFailedImages;
var numImagesTotal = <?php echo count($this->cards); ?>;

function updatePreviewStats()
{
	$("#previewSucceeded").html(numSucceededImages);
	$("#previewFailed").html(numFailedImages);
	$("#previewRemaining").html(numRemainingImages);

	if(numSucceededImages != numImagesTotal)
	{
		$("[name=submit]").prop('disabled', true);
		$("#cardImageCheckResult").show();
	}
	else 
	{
		$("[name=submit]").prop('disabled', false);
		$("#cardImageCheckResult").hide();
	}
}

function cardImageCheck()
{
	numRemainingImages = numImagesTotal;
	numSucceededImages = 0;
	numFailedImages = 0;
	
	updatePreviewStats();

	$("#setPreviewFailureList").empty();
	
	$("#setPreview img").each(function(index) {
		$(this).unbind();
		$(this).attr("src", "/");
		
		$(this).load(function() {
			if(this.error)
			{
				numFailedImages++;
				$("#setPreviewFailureList").append("Could not load card image for \"" + $(this).attr("alt") + "\" from URL \"" + $(this).attr("url") + "\".<br />");
				console.log("Failed: " + $(this).attr("src"));
			}
			else 
			{
				numSucceededImages++;
				console.log("Succeeded: " + $(this).attr("src"));
			}		

			numRemainingImages--;
			
			updatePreviewStats();		
	   	}).error(function() {
			numFailedImages++;
			console.log("Failed: " + $(this).attr("src"));
			$("#setPreviewFailureList").append("Could not load card image for \"" + $(this).attr("alt") + "\" from URL \"" + $(this).attr("url") + "\".<br />");

			numRemainingImages--;
			
			updatePreviewStats();		
	   	});

		$(this).attr("src", $(this).attr("url"));
	});
}

$(document).ready(function(){
	cardImageCheck();

	var simplemde = createEditor('input[name="about"]');
	$("input[name='submit']").click(function(){ hasUnsavedChanges = false; });

	$("input[name='name']").on('input', function(){
		$("input[name='url_name']").val(toUrlName($(this).val()));
	});
});
</script>
<h2 id="contentTitle">New card file for <?php echo $this->set->name ?></h2>
<p>The card file was uploaded and parsed successfully. Please fill in a few more details which will be used to represent this version of the set on PlaneSculptors. During this step, PlaneSculptors will also test whether all card image links work correctly.</p>
<p>Once you submit this form, this version will become the current (and default) version users will see.</p>

<?php
$form = $this->form;

$form->setAttribute('action', $this->url('member-area-manage-set', array('action' => 'create-set-version', 'set_id' => $this->set->setId), array('query' => array('upload' => $this->uploadGuid)))); 
$form->prepare();

$replacementToken = 'XYZ1234';
$url = $this->url('browse-version', array('url_name' => $this->set->urlName, 'version_url_name' => $replacementToken), array('force_canonical' => true));
$url = substr($url, 0, strpos($url, $replacementToken));

echo $this->form()->openTag($form);
echo $this->fullFormInput($form->get('name'));
echo $this->fullFormInput($form->get('url_name'), $url, null, true);
echo $this->fullFormInput($form->get('download_url'));
echo $this->fullFormInput($form->get('about'));
?>
<div class="form_element">
<?php
echo $this->formSubmit($form->get('submit')) . " <span id='cardImageCheckResult'>Card image check did not pass yet. Please make sure all images display correctly before submitting.</span>";
?>
</div>
<?php
echo $this->form()->closeTag();
?>

<div id="setPreview">
<h3>Card image check</h3>
<button onclick="cardImageCheck()">Try again</button>
<div id="setPreviewStats">
	Images succeeded: <span id="previewSucceeded">0</span><br />Images failed: <span id="previewFailed">0</span> <br />Images remaining: <span id="previewRemaining">0</span>
</div>
<div id="setPreviewFailureList">
</div>
<?php foreach($this->cards as $card)
{
	echo "<img url='" . $card->artUrl . "' src=''  alt='" . $card->name . "' />";
}
?>
</div>