<?php $this->headTitle()->append("Manage " . $this->draft->name); ?>
<h2 id="contentTitle"><?php echo $this->draft->name; ?> <img src="<?php echo $this->basePath('images/spinner.svg')?>" alt="Spinner" class="spinner headerSpinner"/></h2>
<?php 
if($this->draftOpened)
{
?>
	<div class="success-message">Event opened!</div>
<?php 
}
if($this->playerKicked)
{
?>
	<div class="success-message">Player kicked!</div>
<?php 
}
?>

<div id="draft_players">Loading...</div>

<script>
var draftStatuses = {"open":1, "running":2, "finished":3};
var lastData = null;
var xhr = null;
var timer = null;

$(document).ready(function(){
	refreshPlayersListExplicit();
});

function addDraftPlayer()
{
	$("#draft_players").html("Loading...");
	$.getJSON( "<?php echo $this->url('member-area-with-draft-id', array('action' => 'add-draft-player', 'draft_id' => $this->draft->draftId));?>", function( data ) {		
		refreshPage();
	});
}

function addAi()
{
	$("#draft_players").html("Loading...");
	$.getJSON( "<?php echo $this->url('member-area-with-draft-id', array('action' => 'add-draft-player', 'draft_id' => $this->draft->draftId));?>?is_ai=1", function( data ) {		
		refreshPage();
	});
}

function refreshPlayersListExplicit()
{
	lastData = null;
	$("#draft_players").html("Loading...");
	refreshPage();
}

function joinAsPlayer() {

}

function refreshPage()
{
	if(timer != null)
	{
		clearTimeout(timer);
	}
	
	if(xhr != null)
	{
		xhr.abort();
		xhr = null;

	}
	
	$('.spinner').show();
	xhr = $.getJSON( "<?php echo $this->url('member-area-with-draft-id', array('action' => 'get-draft-players', 'draft_id' => $this->draft->draftId));?>", function( data ) {
		$('.spinner').hide();
		if(lastData == data){
			timer = setTimeout(function(){ refreshPage(); }, 1000);
			return;
		}

		var hostInviteKey = null;
		$("#draft_players").empty();
		if(data["draft"]["status"] == draftStatuses.open)
		{
			$("#draft_players").append("<p>The event is now open for players to join. Link to lobby for this event:</p>");
			$("#draft_players").append("<input type='text' readonly value='<?php echo $this->url('lobby', array('lobby_key' => $this->draft->lobbyKey), array('force_canonical' => true));?>' class='linkBox' onClick='selectAll(this)'/><br />");
			$("#draft_players").append("<p>Share this link with the players. Below, you can find the list of joined players along with their personal draft links (you can resend the link to the player, in case they lose it).</p>")
			
			if(data["draftPlayers"].length > 0){
				$("#draft_players").append("<p>Joined players:</p>");
			}
			//$("#draft_players").append("<p>Alternatively, you can generate individual links for each player by clicking the \"Add player\" button. The player has to open the link, fill in his player name (or log in) and click \"Join\". </p>");
			//$("#draft_players").append("<button onclick=\"addDraftPlayer()\">Add player</button><button onclick=\"refreshPlayersListExplicit()\">Refresh</button>");
			
			var items = [];
			var humanPlayers = 0;
			$.each( data["draftPlayers"], function( key, val ) {
				if(val["userId"] == <?php echo $this->auth()->getUser()->userId ?>) hostInviteKey = val["inviteKey"];

				var draftLink = val["isAi"] == 1 ? "N/A" : "<?php echo $this->url('home', array(), array('force_canonical' => true));?>draft/" + val["inviteKey"];
				var playerName = (val["isAi"] == 1 ? '<i class="fa fa-microchip"></i> ' : "") + val["name"];
				var url = "<input type='text' readonly value='" + draftLink + "' class='linkBox' onClick='selectAll(this)'/> " + (val["hasJoined"] ? (val["urlName"] != null ? '<a href="/user/' + val["urlName"] + '" target="blank">' + playerName + '</a>' : playerName) : "<i>&lt;PENDING&gt;</i>");

				if(val["hasJoined"]){
					url += " <a href='/member-area/draft/kick/<?php echo $this->draft->draftId ?>?draft_player_id=" + val["draftPlayerId"] + "' class='kick-link' title='Kick this player from the event'>X</a>";
				}
				
				$("#draft_players").append("<div>" + url + "</div>");
				
				$("#start-event").show();
				//alert();

				if(val["isAi"] == 0) {
					humanPlayers++;
				}
			});
			
			if(humanPlayers > 0){
				$("#draft_players").append("<p>When all the players have joined, you can start the event by clicking \"Start event\". Once the event is started, players won't be able to join anymore.");
				$("#draft_players").append("<input type='submit' onclick=\"startDraft()\" value='Start event' id='start-event' />");
			}
			else {
				$("#draft_players").append("<p>At least one human player must join to allow you to start the event.</p>");
			}
		}
		else if(data["draft"]["status"] == draftStatuses.running || data["draft"]["status"] == draftStatuses.finished)
		{
			if(data["draft"]["status"] == draftStatuses.running)
			{
				$("#draft_players").append("<p>The event is now running and players can make their picks. You can obtain their pick/pool lists here. If you are playing in the draft, please don't use this to get an unfair advantage, please :)</p>");
				//$("#draft_players").append("<button onclick=\"refreshPlayersListExplicit()\">Refresh</button><br/>");
				$("#draft_players").append("<p><strong>Pack: " + data["draft"]["packNumber"] + ", pick: " + data["draft"]["pickNumber"] + "</b></p>");
			}
			else {
				$("#draft_players").append("<p>The event has concluded. You can obtain players' pick/pool lists here.</p>");
			}
			
			var items = [];
			$.each( data["draftPlayers"], function( key, val ) {
				if(!val["hasJoined"])
				{
					return;
				}

				if(val["userId"] == <?php echo $this->auth()->getUser()->userId ?>) hostInviteKey = val["inviteKey"];

				var link = val["isAi"] == 1 ? "N/A" : "<?php echo $this->url('home', array(), array('force_canonical' => true));?>draft/" + val["inviteKey"];
				var pickList = val["isAi"] == 1 ? "" : "<small>(<a href='<?php echo $this->url('home', array(), array('force_canonical' => true));?>draft/" + val["inviteKey"] + "/pick-list' target='blank'>pick list</a>)</small>";
				var url = "<input type='text' readonly value='" + link + "' class='linkBox' onClick='selectAll(this)'/> " + (val["urlName"] != null ? '<a href="/user/' + val["urlName"] + '" target="blank">' + val["name"] + '</a>' : val["name"]) + " " + pickList;
				$("#draft_players").append("<div>" + url + "</div>");
			});
		}

		if(hostInviteKey != null) {
			$("#draft_players").append(" <input type='submit' onclick=\"goToDraft('" + hostInviteKey + "')\" value='Go to your&nbsp;draft' />");
		}
		else {
			$("#draft_players").append(" <input type='submit' onclick=\"joinDraft()\" value='Join as a player' />");
		}

		if(data["draft"]["status"] >= draftStatuses.running){
			if(data["draft"]["tournamentUrl"] != null)
			{	
				$("#draft_players").append(" <input type='submit' onclick=\"window.location='"+ data["draft"]["tournamentUrl"] +"'\" value='Go to tournament' />");
			}
			else {
				$("#draft_players").append(" <input type='submit' onclick=\"window.location='<?php echo $this->url('member-area-with-draft-id', array('action' => 'create-tournament', 'draft_id' => $this->draft->draftId));?>'\" value='Host a tournament' />");
			}
		}	
		else
		{
			$("#draft_players").append(" <input type='submit' onclick=\"addAi()\" value='Add AI player' />");
		}	

		timer = setTimeout(function(){ refreshPage(); }, 1000);
	});
}

function startDraft()
{
	if(xhr != null) xhr.abort();
	if(timer != null) clearTimeout(timer);
	$("#draft_players").html("Loading...");
	$.getJSON( "<?php echo $this->url('member-area-with-draft-id', array('action' => 'start-draft', 'draft_id' => $this->draft->draftId));?>", function( data ) {		
		refreshPlayersListExplicit();
	});
}

function joinDraft()
{
	if(xhr != null) xhr.abort();
	if(timer != null) clearTimeout(timer);
	window.location = '<?php echo $this->url('lobby', array('action' => 'join', 'lobby_key' => $this->draft->lobbyKey)); ?>';
}

function goToDraft(hostInviteKey)
{
	if(xhr != null) xhr.abort();
	if(timer != null) clearTimeout(timer);
	window.location = "/draft/" + hostInviteKey;
}

</script>