<?php $this->headTitle()->append("Member area"); ?>
<script>
$(function(){
	$('#owned-sets-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 9999
	});
	
});
</script>
<h2 id="contentTitle">Choose a set to update</h2>
<p>All files were uploaded, please choose which set should be updated. If you want to cancel this upload, just close this page.</p>
<div id="owned-sets">
<form action="#">
	<table id="owned-sets-grid" class="display hover stripe" >
		<thead>
			<tr>
				<th>Set name</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
	<?php
	foreach ($this->setsOwned as $set)
	{
		$setId = $set["setId"];
		echo "<tr><td class='nameCell'>";
		echo $set["setName"];
		echo "</td><td><button type='submit' name='setId' value='$setId' class='add-button'>Choose</button></td></tr>";	
	}
	?>
			</tr>
		</tbody>
	</table>
</form>
</div>