<h2>Host an event</h2>
<!--  <button>Add pack</button>-->
<?php
$form = $this->form;
$formLabel = $this->plugin('formLabel');

$form->setAttribute('action', $this->url('member-area', array('action' => 'host-draft'))); 
$form->prepare();
 
echo $this->form()->openTag($form);
echo $this->formElement($form->get('mode'));
echo $this->formElement($form->get('number_of_packs'));

for($i = 1; $i <= $form->get('number_of_packs')->getvalue(); $i++)
{
?>
<div class="form_element">
<?php
    $pack = $form->get('pack' . $i);
    echo $formLabel->openTag() /*. $pack->getOption('label')*/;
    echo $this->formElement($pack);
    echo $this->formElementErrors($pack) /*. "<small>" . $pack->getOption('description') . "</small>"*/;
    echo $formLabel->closeTag();
?>
</div>
<?php 
}
?>
<div class="form_element">
<?php
/*
    $mode = $form->get('mode');
    echo $formLabel->openTag() . $mode->getOption('label');
    echo $this->formElement($mode);
    echo $this->formElementErrors($mode) . "<small>" . $mode->getOption('description') . "</small>";
    echo $formLabel->closeTag();*/
?>
</div>
<div class="form_element">
<?php
echo $this->formSubmit($form->get('submit')) . '<small>' . $form->get('submit')->getOption('description') . '</small>';
?>
</div>
<?php
echo $this->form()->closeTag();