<?php $this->headTitle()->append("Member area"); ?>
<script>
$(function(){
	makeTabs($("#tabs"));
	
	$('#owned-sets-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15
	});
	
	$('#hosted-events-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15,
		"order": [[ 1, "desc" ]]
	});
	
	$('#played-events-grid').DataTable({
		"searching": false,
		"lengthChange": false,
		"pageLength": 15,
		"order": [[ 1, "desc" ]]
	});

	$('.dataTable').on( 'click', 'tr', function () {
		$(this).addClass('selected');
		if($(this).attr('url') != null)
		{
			window.location = $(this).attr('url');
		}
	});
});
</script>
<h2 id="contentTitle">Member area</h2>
<?php 
if($this->setCreated)
{
?>
	<div class="success-message"/>Set created!</div>
<?php 
}

if($this->setRetired)
{
	?>
	<div class="success-message"/>Set retired!</div>
<?php 
}

if($this->accountUpdated)
{
	?>
	<div class="success-message"/>Account settings changed!</div>
<?php 
}

?>

<div id="tabs">
	<ul>
		<li><a href="#played-events">Played events</a></li>
		<li><a href="#hosted-events">Hosted events</a></li>
		<li><a href="#owned-sets">Owned sets</a></li>
		<li><a href="#account-settings">Account settings</a></li>
	</ul>
	<div id="played-events">
		<p>This page contains an overview of drafts and other events you played in.</p>		
		<table id="played-events-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>Event name</th>
					<th>Date and time</th>
					<th>Host</th>
					<th>Status</th>
					<th>Number of players</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->draftsPlayed as $draft)
		{
			echo "<tr url='" . $this->url('draft', array('invite_key' => $draft["inviteKey"])) . "'><td class='nameCell'>";
			echo $draft["draftName"];
		
			echo "</td><td>";
			echo $draft["createdOn"];	
			echo "</td><td>";
			echo $draft["hostName"];				
			echo "</td><td>";
			switch($draft["draftStatus"])
			{
				case \Application\Model\Draft::STATUS_OPEN:
					echo "OPEN";
					break;
				case \Application\Model\Draft::STATUS_RUNNING:
					echo "RUNNING - pack " . $draft["packNumber"] . ", pick " . $draft["packNumber"];
					break;
				case \Application\Model\Draft::STATUS_FINISHED:
					echo "FINISHED";
					break;
			}
			echo "</td><td>" . $draft["playerCount"] . "</td></tr>";
		}
		?>
			</tbody>
		</table>
	</div>
	<div id="hosted-events">
		<p>This page contains an overview of drafts and other events you hosted.</p>		
		<table id="hosted-events-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>Event name</th>
					<th>Date and time</th>
					<th>Status</th>
					<th>Number of players</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->draftsHosted as $draft)
		{
			echo "<tr url='" . $this->url('member-area-with-draft-id', array('action' => 'draft-admin', 'draft_id' => $draft["draftId"])) . "'><td class='nameCell'>";
			echo $draft["draftName"];
		
			echo "</td><td>";
			echo $draft["createdOn"];			
			echo "</td><td>";
			switch($draft["draftStatus"])
			{
				case \Application\Model\Draft::STATUS_OPEN:
					echo "OPEN";
					break;
				case \Application\Model\Draft::STATUS_RUNNING:
					echo "RUNNING - pack " . $draft["packNumber"] . ", pick " . $draft["pickNumber"];
					break;
				case \Application\Model\Draft::STATUS_FINISHED:
					echo "FINISHED";
					break;
			}
			
			echo "</td><td>" . $draft["playerCount"] . "</td></tr>";
		}
		?>
			</tbody>
		</table>
	</div>
	<div id="owned-sets">
		<p>This page contains an overview of sets you own.</p>
		<a href="<?php echo $this->url('member-area', array('action' => 'create-set'));?>">Create a new set</a><br/>
		<table id="owned-sets-grid" class="display hover stripe clickableRows" >
			<thead>
				<tr>
					<th>Set name</th>
					<th>Number of cards</th>
					<th>Number of events</th>
				</tr>
			</thead>
			<tbody>
		<?php
		foreach ($this->setsOwned as $set)
		{
			echo "<tr url='" . $this->url('member-area-manage-set', array('set_id' => $set["setId"])) . "'><td class='nameCell'>";
			echo $set["setName"];
			echo "</td><td>" . $set["cardCount"] . "</td><td>" . $set["draftCount"] . "</td></tr>";	
		}
		?>
				</tr>
			</tbody>
		</table>
	</div>
	<div id="account-settings">	
		<p><strong>API key:</strong> <br/><?php echo $this->user->apiKey ?></p>
		<?php echo $this->partial('/application/member-area/register', array('form' => $this->form, 'registrationMode' => false)); ?>
	</div>
</div>