<script>
function updateNeedle(){
	var mode = $("select[name='basic_land_slot']").val();
	var needleNeeded = mode == <?php echo \Application\Model\SetVersion::BASIC_LAND_SLOT_TYPE ?> || mode == <?php echo \Application\Model\SetVersion::BASIC_LAND_SLOT_RULES_TEXT ?>;
	if(needleNeeded){
		$("#basic-land-slot-needle").show();
	}
	else {
		$("#basic-land-slot-needle").hide();
	}
}

$(function(){
	var simplemde = createEditor('input[name="about"]');
	$("input[name='submit']").click(function(){ hasUnsavedChanges = false; });

	$("input[name='name']").on('input', function(){
		$("input[name='url_name']").val(toUrlName($(this).val()));
	});

	$("select[name='basic_land_slot']").change(updateNeedle);
	updateNeedle();
});
</script>

<h2 id="contentTitle"><a href="<?php echo $this->url('member-area-manage-set', array('set_id' => $this->set->setId))?>"><?php echo $this->set->name ?></a> (<?php echo $this->setVersion->name ?>)</h2>
<?php 
if($this->changesSaved)
{
	?>
	<div class="success-message"/>Changes saved!</div>
<?php 
}

$form = $this->form;
 
$form->prepare();

echo $this->form()->openTag($form);

$replacementToken = 'XYZ1234';
$url = $this->url('browse-version', array('url_name' => $set->urlName, 'version_url_name' => $replacementToken), array('force_canonical' => true));
$url = substr($url, 0, strpos($url, $replacementToken));

echo $this->fullFormInput($form->get('name'));
echo $this->fullFormInput($form->get('url_name'), $url, null, true);
echo $this->fullFormInput($form->get('basic_land_slot'), null, '<span id="basic-land-slot-needle"> <span>String to look for: </span>'.$this->formElement($form->get('basic_land_slot_needle')).'</span>');
echo $this->fullFormInput($form->get('about'));

?>
<div class="form_element">
<?php
echo $this->formSubmit($form->get('submit'));
?>
</div>

<?php
echo $this->form()->closeTag();
?>