<script>
$(document).ready(function(){
	var simplemde = new SimpleMDE({ element: $('input[name="about"]')[ 0 ], status: false });

	$("input[name='name']").on('input', function(){
		$("input[name='url_name']").val(toUrlName($(this).val()));
	});
});
</script>
<?php if($this->registrationMode){?>
	<h2 id="contentTitle">User registration</h2>
	<p>This is the first time you are logging into WebDrafter. We need you to fill in a few things before you can continue to use the app.</p>
<?php
}
$form = $this->form;
$formLabel = $this->plugin('formLabel');
$form->prepare();

echo $this->form()->openTag($form);
if($this->registrationMode){
	echo $this->fullFormInput($form->get('name'));
	echo $this->fullFormInput($form->get('url_name'));
}
echo $this->fullFormInput($form->get('email_privacy'));
echo $this->fullFormInput($form->get('about'));
?>
<div class="form_element">
<?php
echo $this->formSubmit($form->get('submit'));
?>
</div>
<?php
echo $this->form()->closeTag();