<h2 id="contentTitle">Select game mode</h2>
<h3><a href="<?php echo $this->url('member-area', array('action' => 'host-draft'), array('query' => 'mode=' . \Application\Model\Draft::MODE_BOOSTER_DRAFT)) ?>">Booster draft</a></h3>
Each player receives packs from the same sets. All the packs are standard booster packs (they contain a random rare or mythic, three random uncommons and ten random commons).

<h3><a href="<?php echo $this->url('member-area', array('action' => 'host-draft'), array('query' => 'mode=' . \Application\Model\Draft::MODE_CHAOS_DRAFT)) ?>">Chaos draft</a></h3>
Each player receives packs from a random pool of boosters from various sets. All the packs are standard booster packs (they contain a random rare or mythic, three random uncommons and ten random commons).

<h3><a href="<?php echo $this->url('member-area', array('action' => 'host-draft'), array('query' => 'mode=' . \Application\Model\Draft::MODE_CUBE_DRAFT)) ?>">Cube draft</a></h3>
Each card can appear only once in the entire draft. Card rarities are not in effect.

<h3><a href="<?php echo $this->url('member-area', array('action' => 'host-draft'), array('query' => 'mode=' . \Application\Model\Draft::MODE_SEALED_DECK)) ?>">Sealed deck</a></h3>
Players open their packs without drafting them. Each player receives packs from the same sets. All the packs are standard booster packs (they contain a random rare or mythic, three random uncommons and ten random commons).