WebDrafter is a web application where you can draft custom Magic: the Gathering sets. Feel free to upload your set and organize some drafts or sealed deck events!

<p>Do you need players for your event? Ask around on <a href="https://client01.chat.mibbit.com/?channel=%23custommagic&server=irc.synirc.net">#CustomMagic IRC channel</a>!</p>

<p><a href="browse">Browse sets</a></p>
<p><a href="https://trello.com/b/olnCSJQC/webdrafter">View issues and TODO</a></p>
<p><a href="https://github.com/mzabsky/webdrafter">Source code</a></p>

<p>If you have any feedback, contact me at <a href="mailto:mzabsky@gmail.com">mzabsky@gmail.com</a>.</p>

<h2>Host an event</h2>
To host an event or to upload a set, <a href="<?php echo $this->url('member-area', array('action' => 'login'))?>">login</a> with Google.

<h2>Join an event</h2>
To join an event, open the link provided to you by your event organizer.